name: Update Pre with Main

on:
  push:
    branches:
      - main

jobs:
  updatepre:
    name: Update Pre with changes from Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create Pull Request
        uses: gha-utilities/init-pull-request@v0.1.0
        with:
          pull_request_token: ${{ secrets.GH_TOKEN }}
          head: main
          base: pre
          title: Update Pre with changes from Main
